
DROP TABLE NOTIFICATION         CASCADE CONSTRAINTS PURGE;
DROP TABLE COMPLAINT            CASCADE CONSTRAINTS PURGE;
DROP TABLE REVIEW               CASCADE CONSTRAINTS PURGE;
DROP TABLE BAZAR_DAILY_RECORD   CASCADE CONSTRAINTS PURGE;
DROP TABLE PHYSICAL_BAZAR       CASCADE CONSTRAINTS PURGE;
DROP TABLE DAILY_MARKET_PRICE   CASCADE CONSTRAINTS PURGE;
DROP TABLE ASSIGNED_TO          CASCADE CONSTRAINTS PURGE;
DROP TABLE TRANSPORT_REQUEST    CASCADE CONSTRAINTS PURGE;
DROP TABLE VEHICLE              CASCADE CONSTRAINTS PURGE;
DROP TABLE PAYMENT              CASCADE CONSTRAINTS PURGE;
DROP TABLE STORES               CASCADE CONSTRAINTS PURGE;
DROP TABLE SALE_ORDER           CASCADE CONSTRAINTS PURGE;
DROP TABLE BID                  CASCADE CONSTRAINTS PURGE;
DROP TABLE STORAGE_UNIT         CASCADE CONSTRAINTS PURGE;
DROP TABLE WAREHOUSE            CASCADE CONSTRAINTS PURGE;
DROP TABLE HARVEST_BATCH        CASCADE CONSTRAINTS PURGE;
DROP TABLE VIRTUAL_ARAT         CASCADE CONSTRAINTS PURGE;
DROP TABLE FARM                 CASCADE CONSTRAINTS PURGE;
DROP TABLE CROP                 CASCADE CONSTRAINTS PURGE;
DROP TABLE CROP_CATEGORY        CASCADE CONSTRAINTS PURGE;
DROP TABLE TRANSPORT_PERSONNEL  CASCADE CONSTRAINTS PURGE;
DROP TABLE STORAGE_MANAGER      CASCADE CONSTRAINTS PURGE;
DROP TABLE ADMIN_STAFF          CASCADE CONSTRAINTS PURGE;
DROP TABLE BUYER                CASCADE CONSTRAINTS PURGE;
DROP TABLE FARMER               CASCADE CONSTRAINTS PURGE;
DROP TABLE USER_PHONE           CASCADE CONSTRAINTS PURGE;
DROP TABLE USERS                CASCADE CONSTRAINTS PURGE;

BEGIN
  FOR t IN (SELECT type_name FROM user_types) LOOP
    EXECUTE IMMEDIATE 'DROP TYPE ' || t.type_name || ' FORCE';
  END LOOP;
END;
/

SELECT COUNT(*) AS tables_remaining    FROM user_tables;
SELECT COUNT(*) AS types_remaining     FROM user_types;
SELECT COUNT(*) AS recycle_bin_objects FROM recyclebin;
